# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.10
_src_path: gh:algorandfoundation/algokit-python-template
author_email: obafemijoshua2020@gmail.com
author_name: Joshua Obafemi
contract_name: algo_marketplace
deployment_language: python
preset_name: production
project_name: algo_marketplace

